name: Set Up Clang/LLVM
description: "This composite action installs Clang/LLVM to the runner's temporary directory and sets LIBCLANG_PATH for the following steps, which is required for bindgen to work on Windows. See: https://github.com/rust-lang/rust-bindgen/issues/1797."
inputs:
  version:
    description: The version of Clang/LLVM to install.
    type: string
    required: false
    default: '13'

runs:
  using: composite
  steps:
    - name: Install Clang/LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{ inputs.version }}
        directory: ${{ runner.temp }}/llvm/

    - name: Set LIBCLANG_PATH
      shell: pwsh
      run: Add-Content -Path "$Env:GITHUB_ENV" -Value "LIBCLANG_PATH=$Env:LLVM_PATH\bin"
